# Generated by Django 5.2.6 on 2025-10-08 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='is_social_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuser',
            name='phone',
            field=models.CharField(default='+8801', max_length=20, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
    ]
