# Generated by Django 5.2.6 on 2025-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cuser_is_social_login_cuser_phone_alter_cuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuser',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('center_owner', 'Center-Owner'), ('admin_user', 'Admin-User')], max_length=20),
        ),
    ]
