# Generated by Django 5.2.6 on 2025-10-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark if the user has verified their account.'),
        ),
    ]
