# Generated by Django 5.2.6 on 2025-10-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='cuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuser',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
