# Generated by Django 5.2.6 on 2025-10-11 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cuser_is_verified_cuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuser',
            old_name='verification_code',
            new_name='verification_token',
        ),
        migrations.AlterField(
            model_name='cuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cuser',
            name='phone',
            field=models.CharField(default='+8801', max_length=20, unique=True),
        ),
    ]
