# Generated by Django 5.2.6 on 2025-10-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_verification_code_cuser_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
