# Generated by Django 5.2.6 on 2025-10-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sliderimage_websiteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='core.websiteconfiguration'),
        ),
    ]
