# Generated by Django 5.2.6 on 2025-10-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sliderimage_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='caption_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
