# Generated by Django 5.2.6 on 2025-10-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sliderimage_caption_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfiguration',
            name='logo_size',
            field=models.CharField(default='50', max_length=150),
        ),
    ]
