# Generated by Django 5.2.6 on 2025-10-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_websiteconfiguration_logo_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Marriage', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
