# Generated by Django 5.2.6 on 2025-09-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of persons')),
                ('area_size', models.CharField(blank=True, max_length=50, null=True)),
                ('parking_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.DateField(blank=True, null=True)),
                ('is_government_property', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hall_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.hall')),
            ],
        ),
        migrations.CreateModel(
            name='HallRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('nov_jan', 'November – January'), ('feb_oct', 'February – October')], max_length=20)),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('full', 'Day & Night Shift')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='services.hall')),
            ],
            options={
                'unique_together': {('hall', 'season', 'shift')},
            },
        ),
    ]
