# Generated by Django 5.2.6 on 2025-09-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='batch',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of persons can dine'),
        ),
    ]
