# Generated by Django 5.2.6 on 2025-09-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.ImageField(default='hall_images/default_icon.png', upload_to='hall_images/'),
        ),
    ]
