# Generated by Django 5.2.6 on 2025-09-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_hall_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
