# Generated by Django 5.2.6 on 2025-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_amenity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='address',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
