# Generated by Django 5.2.6 on 2025-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_center_address_alter_center_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
