# Generated by Django 5.2.6 on 2025-10-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallimage',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_images', to='services.center'),
        ),
        migrations.AlterField(
            model_name='hallimage',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_images', to='services.hall'),
        ),
    ]
