# Generated by Django 5.2.6 on 2025-10-04 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_hallimage_center_alter_hallimage_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallimage',
            name='hall',
        ),
    ]
