# Generated by Django 5.2.6 on 2025-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_center_address_alter_center_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100, null=True),
        ),
    ]
