# Generated by Django 5.2.6 on 2025-10-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_center_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hallamenity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hallamenity',
            name='center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='center_amenities', to='services.center'),
        ),
        migrations.AddConstraint(
            model_name='hallamenity',
            constraint=models.UniqueConstraint(fields=('center', 'amenity'), name='unique_center_amenity'),
        ),
        migrations.RemoveField(
            model_name='hallamenity',
            name='hall',
        ),
    ]
