# Generated by Django 5.2.6 on 2025-10-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_hallamenity_unique_together_hallamenity_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='services.amenity'),
        ),
    ]
