# Generated by Django 5.2.6 on 2025-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_center_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='centers', to='services.amenity'),
        ),
    ]
