# Generated by Django 5.2.6 on 2025-10-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_center_amenities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HallAmenity',
        ),
    ]
