# Generated by Django 5.2.6 on 2025-10-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_delete_hallamenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='batch',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
