# services/bangladesh_locations.py

BANGLADESH_DISTRICTS = [
    ("Dhaka", "Dhaka"),
    ("Gazipur", "Gazipur"),
    ("Narayanganj", "Narayanganj"),
    ("Tangail", "Tangail"),
    ("Kishoreganj", "Kishoreganj"),
    ("Manikganj", "Manikganj"),
    ("Narsingdi", "Narsingdi"),
    ("Munshiganj", "Munshiganj"),
    ("Mymensingh", "Mymensingh"),
    ("Jamalpur", "Jamalpur"),
    ("Sherpur", "Sherpur"),
    ("Netrokona", "Netrokona"),
    ("Chittagong", "Chittagong"),
    ("Cox's Bazar", "Cox's Bazar"),
    ("Comilla", "Comilla"),
    ("Feni", "Feni"),
    ("Noakhali", "Noakhali"),
    ("Brahmanbaria", "Brahmanbaria"),
    ("Chandpur", "Chandpur"),
    ("Rangamati", "Rangamati"),
    ("Khagrachhari", "Khagrachhari"),
    ("Bandarban", "Bandarban"),
    ("Sylhet", "Sylhet"),
    ("Moulvibazar", "Moulvibazar"),
    ("Habiganj", "Habiganj"),
    ("Sunamganj", "Sunamganj"),
    ("Rajshahi", "Rajshahi"),
    ("Natore", "Natore"),
    ("Pabna", "Pabna"),
    ("Sirajganj", "Sirajganj"),
    ("Bogra", "Bogra"),
    ("Joypurhat", "Joypurhat"),
    ("Naogaon", "Naogaon"),
    ("Chapainawabganj", "Chapainawabganj"),
    ("Khulna", "Khulna"),
    ("Jessore", "Jessore"),
    ("Satkhira", "Satkhira"),
    ("Bagerhat", "Bagerhat"),
    ("Kushtia", "Kushtia"),
    ("Jhenaidah", "Jhenaidah"),
    ("Magura", "Magura"),
    ("Chuadanga", "Chuadanga"),
    ("Meherpur", "Meherpur"),
    ("Barisal", "Barisal"),
    ("Patuakhali", "Patuakhali"),
    ("Bhola", "Bhola"),
    ("Barguna", "Barguna"),
    ("Jhalokathi", "Jhalokathi"),
    ("Pirojpur", "Pirojpur"),
    ("Rangpur", "Rangpur"),
    ("Kurigram", "Kurigram"),
    ("Lalmonirhat", "Lalmonirhat"),
    ("Nilphamari", "Nilphamari"),
    ("Gaibandha", "Gaibandha"),
    ("Dinajpur", "Dinajpur"),
    ("Thakurgaon", "Thakurgaon"),
    ("Panchagarh", "Panchagarh"),
]

# Optional — short city list (if you want to separate city dropdown)
BANGLADESH_CITIES = [
    ("Dhaka", "Dhaka"),
    ("Chittagong", "Chittagong"),
    ("Sylhet", "Sylhet"),
    ("Rajshahi", "Rajshahi"),
    ("Khulna", "Khulna"),
    ("Barisal", "Barisal"),
    ("Rangpur", "Rangpur"),
    ("Mymensingh", "Mymensingh"),
]
