# Generated by Django 5.2.6 on 2025-10-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_address'),
        ('core', '0012_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='shift',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('day_and_night', 'Full Day')], default='day_and_night', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_event_type', to='core.eventtype'),
        ),
    ]
